# Generated by Django 5.1.4 on 2025-03-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chai_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chai_name', models.CharField(max_length=100)),
                ('chai_price', models.FloatField()),
                ('chai_description', models.TextField(blank=True)),
                ('coffee_img', models.ImageField(blank=True, null=True, upload_to='chai_img/')),
            ],
        ),
        migrations.CreateModel(
            name='coffee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_name', models.CharField(max_length=100)),
                ('coffe_price', models.FloatField()),
                ('coffee_description', models.TextField(blank=True)),
                ('coffee_img', models.ImageField(blank=True, null=True, upload_to='coffee_img/')),
            ],
        ),
    ]
