# Generated by Django 5.1.4 on 2025-03-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee_details',
            old_name='coffe_price',
            new_name='coffee_price',
        ),
        migrations.AlterField(
            model_name='chai_details',
            name='coffee_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/chai_img'),
        ),
        migrations.AlterField(
            model_name='coffee_details',
            name='coffee_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/coffee_img'),
        ),
    ]
