# Generated by Django 5.1.4 on 2025-03-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0002_rename_coffe_price_coffee_details_coffee_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chai_details',
            name='coffee_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/chaii_img'),
        ),
        migrations.AlterField(
            model_name='coffee_details',
            name='coffee_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/coffeeImages'),
        ),
    ]
