# Generated by Django 5.1.4 on 2025-03-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0003_alter_chai_details_coffee_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chai_details',
            name='coffee_img',
            field=models.ImageField(blank=True, null=True, upload_to='chaii_img'),
        ),
        migrations.AlterField(
            model_name='coffee_details',
            name='coffee_img',
            field=models.ImageField(blank=True, null=True, upload_to='coffeeImages'),
        ),
    ]
