# Generated by Django 5.1.4 on 2025-03-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0004_alter_chai_details_coffee_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chai_details',
            old_name='coffee_img',
            new_name='chai_img',
        ),
    ]
